version: '3'

secrets:
  ssh_key:
    file: ~/.ssh/id_rsa

services:

  ####### PHP ######
  dev-server:
    build:
      context: .
      dockerfile: .docker/php8.dev.dockerfile
    environment:
      - TZ=America/Chicago
    ports:
      - 8001:80
    volumes:
      - ./app:/app
      - ./.docker/php.ini/php8.ini:/usr/local/etc/php/php.ini
    command: bash -c 'export XDEBUG_MODE=debug,develop XDEBUG_CONFIG="remote_enable=on"; php -S 0.0.0.0:80 -t /app/html'
    secrets:
      - source: ssh_key
        target: /home/user/.ssh/id_rsa

  prod-server:
    build:
      context: .
      dockerfile: .docker/php8.prod.dockerfile
    environment:
      - TZ=America/Chicago
    ports:
      - 8002:80
    volumes:
      - ./app:/var/www
      - ./app/html:/var/www/html

  ####### Maria DB ########
  db:
    image: mariadb
    environment:
      - TZ=America/Chicago
      - MYSQL_ROOT_PASSWORD=i57z9*UIuJQ!
      - collation-server=utf8mb4_unicode_ci
      - character-set-server=utf8mb4
      - MYSQL_DATABASE=database_name
    ports:
      - 5000:3306
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - TZ=America/Chicago
      - PMA_USER=root
      - PMA_PASSWORD=i57z9*UIuJQ!
    ports:
      - 9082:80

  ####### Redis #######
  redis:
    image: redis
  phpredisadmin:
    image:  erikdubbelboer/phpredisadmin
    environment:
      - TZ=America/Chicago
      - REDIS_1_HOST=redis
    ports:
      - 9083:80

  ######## Apache AB #######
  performance-testing:
    image: httpd
    environment:
      - TZ=America/Chicago
    volumes:
      - ./performance-testing/:/usr/local/apache2/performance-testing
    ports:
      - 9084:80


